version: 3

vars:
  PYTHON_VERSION: "3.13"

tasks:
  default:
    desc: "Default task to run when no task is specified."
    cmd: task --list

  init:
    desc: "Initialize the project by installing dependencies."
    cmds:
      - uv python install {{.PYTHON_VERSION}} --compile-bytecode
      - uv venv --python {{.PYTHON_VERSION}} --clear
      - uv sync --compile-bytecode
